// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contests.sql

package db

import (
	"context"
)

const getContestBySlug = `-- name: GetContestBySlug :one
SELECT id, title, slug, start_at, end_at, is_public, created_at, updated_at
FROM contests
WHERE slug = $1
`

func (q *Queries) GetContestBySlug(ctx context.Context, slug string) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestBySlug, slug)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StartAt,
		&i.EndAt,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContestParticipants = `-- name: ListContestParticipants :many
SELECT id, contest_id, user_id, registered_at, status
FROM contest_participants
WHERE contest_id = $1
ORDER BY registered_at ASC, id ASC
`

func (q *Queries) ListContestParticipants(ctx context.Context, contestID int64) ([]ContestParticipant, error) {
	rows, err := q.db.Query(ctx, listContestParticipants, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestParticipant
	for rows.Next() {
		var i ContestParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.RegisteredAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT contest_id, problem_id, alias, order_index, score
FROM contest_problems
WHERE contest_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListContestProblems(ctx context.Context, contestID int64) ([]ContestProblem, error) {
	rows, err := q.db.Query(ctx, listContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestProblem
	for rows.Next() {
		var i ContestProblem
		if err := rows.Scan(
			&i.ContestID,
			&i.ProblemID,
			&i.Alias,
			&i.OrderIndex,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicContests = `-- name: ListPublicContests :many
SELECT id, title, slug, start_at, end_at, is_public, created_at, updated_at
FROM contests
WHERE is_public = true
ORDER BY start_at DESC, id DESC
`

func (q *Queries) ListPublicContests(ctx context.Context) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listPublicContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.StartAt,
			&i.EndAt,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerContestParticipant = `-- name: RegisterContestParticipant :one
INSERT INTO contest_participants (contest_id, user_id, status)
VALUES ($1, $2, 'registered')
ON CONFLICT (contest_id, user_id)
DO UPDATE SET status = 'registered', registered_at = now()
RETURNING id, contest_id, user_id, registered_at, status
`

type RegisterContestParticipantParams struct {
	ContestID int64 `json:"contest_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RegisterContestParticipant(ctx context.Context, arg RegisterContestParticipantParams) (ContestParticipant, error) {
	row := q.db.QueryRow(ctx, registerContestParticipant, arg.ContestID, arg.UserID)
	var i ContestParticipant
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.RegisteredAt,
		&i.Status,
	)
	return i, err
}
