// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextJudgeJob = `-- name: ClaimNextJudgeJob :one
SELECT id, submission_id, status, priority, attempts, locked_by, locked_at, created_at, updated_at
FROM judge_jobs
WHERE status = 'queued'
ORDER BY priority DESC, created_at ASC
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) ClaimNextJudgeJob(ctx context.Context) (JudgeJob, error) {
	row := q.db.QueryRow(ctx, claimNextJudgeJob)
	var i JudgeJob
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJudgeJob = `-- name: CompleteJudgeJob :exec
UPDATE judge_jobs
SET status = 'completed', locked_by = NULL, locked_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJudgeJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJudgeJob, id)
	return err
}

const createJudgeJob = `-- name: CreateJudgeJob :one
INSERT INTO judge_jobs (submission_id, status, priority)
VALUES ($1, 'queued', $2)
RETURNING id, submission_id, status, priority, attempts, locked_by, locked_at, created_at, updated_at
`

type CreateJudgeJobParams struct {
	SubmissionID int64 `json:"submission_id"`
	Priority     int32 `json:"priority"`
}

func (q *Queries) CreateJudgeJob(ctx context.Context, arg CreateJudgeJobParams) (JudgeJob, error) {
	row := q.db.QueryRow(ctx, createJudgeJob, arg.SubmissionID, arg.Priority)
	var i JudgeJob
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJudgeJob = `-- name: FailJudgeJob :exec
UPDATE judge_jobs
SET status = 'failed', locked_by = NULL, locked_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) FailJudgeJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, failJudgeJob, id)
	return err
}

const markJudgeJobRunning = `-- name: MarkJudgeJobRunning :one
UPDATE judge_jobs
SET status = 'running',
    attempts = attempts + 1,
    locked_by = $2,
    locked_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, submission_id, status, priority, attempts, locked_by, locked_at, created_at, updated_at
`

type MarkJudgeJobRunningParams struct {
	ID       int64       `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) MarkJudgeJobRunning(ctx context.Context, arg MarkJudgeJobRunningParams) (JudgeJob, error) {
	row := q.db.QueryRow(ctx, markJudgeJobRunning, arg.ID, arg.LockedBy)
	var i JudgeJob
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueStaleJudgeJobs = `-- name: RequeueStaleJudgeJobs :execrows
UPDATE judge_jobs
SET status = 'queued',
    locked_by = NULL,
    locked_at = NULL,
    updated_at = now()
WHERE status = 'running'
  AND locked_at < now() - ($1::double precision * interval '1 second')
`

func (q *Queries) RequeueStaleJudgeJobs(ctx context.Context, dollar_1 float64) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleJudgeJobs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
