// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package db

import (
	"context"
)

const getLanguageByID = `-- name: GetLanguageByID :one
SELECT id, name, version, source_file_name, compile_command, run_command,
       time_limit_multiplier, memory_limit_multiplier, is_active, created_at, updated_at
FROM languages
WHERE id = $1
`

func (q *Queries) GetLanguageByID(ctx context.Context, id int64) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguageByID, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.SourceFileName,
		&i.CompileCommand,
		&i.RunCommand,
		&i.TimeLimitMultiplier,
		&i.MemoryLimitMultiplier,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveLanguages = `-- name: ListActiveLanguages :many
SELECT id, name, version, source_file_name, compile_command, run_command,
       time_limit_multiplier, memory_limit_multiplier, is_active, created_at, updated_at
FROM languages
WHERE is_active = true
ORDER BY id ASC
`

func (q *Queries) ListActiveLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listActiveLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.SourceFileName,
			&i.CompileCommand,
			&i.RunCommand,
			&i.TimeLimitMultiplier,
			&i.MemoryLimitMultiplier,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
