// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID           int64              `json:"id"`
	ActorUserID  pgtype.Int8        `json:"actor_user_id"`
	TargetUserID pgtype.Int8        `json:"target_user_id"`
	Action       string             `json:"action"`
	OldValue     pgtype.Text        `json:"old_value"`
	NewValue     pgtype.Text        `json:"new_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Contest struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Slug      string             `json:"slug"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	IsPublic  bool               `json:"is_public"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ContestParticipant struct {
	ID           int64              `json:"id"`
	ContestID    int64              `json:"contest_id"`
	UserID       int64              `json:"user_id"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	Status       string             `json:"status"`
}

type ContestProblem struct {
	ContestID  int64  `json:"contest_id"`
	ProblemID  int64  `json:"problem_id"`
	Alias      string `json:"alias"`
	OrderIndex int32  `json:"order_index"`
	Score      int32  `json:"score"`
}

type JudgeJob struct {
	ID           int64              `json:"id"`
	SubmissionID int64              `json:"submission_id"`
	Status       string             `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	LockedBy     pgtype.Text        `json:"locked_by"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Language struct {
	ID                    int64              `json:"id"`
	Name                  string             `json:"name"`
	Version               string             `json:"version"`
	SourceFileName        string             `json:"source_file_name"`
	CompileCommand        pgtype.Text        `json:"compile_command"`
	RunCommand            string             `json:"run_command"`
	TimeLimitMultiplier   float64            `json:"time_limit_multiplier"`
	MemoryLimitMultiplier float64            `json:"memory_limit_multiplier"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Problem struct {
	ID                int64              `json:"id"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	UserAgent        string             `json:"user_agent"`
	IpAddress        string             `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type Submission struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	ProblemID   int64              `json:"problem_id"`
	LanguageID  int64              `json:"language_id"`
	SourceCode  string             `json:"source_code"`
	Status      string             `json:"status"`
	Score       int32              `json:"score"`
	MaxTimeMs   int32              `json:"max_time_ms"`
	MaxMemoryKb int32              `json:"max_memory_kb"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	JudgedAt    pgtype.Timestamptz `json:"judged_at"`
}

type SubmissionResult struct {
	ID              int64              `json:"id"`
	SubmissionID    int64              `json:"submission_id"`
	TestCaseID      pgtype.Int8        `json:"test_case_id"`
	Status          string             `json:"status"`
	ExecutionTimeMs int32              `json:"execution_time_ms"`
	MemoryKb        int32              `json:"memory_kb"`
	StdoutPath      pgtype.Text        `json:"stdout_path"`
	StderrPath      pgtype.Text        `json:"stderr_path"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TestCase struct {
	ID         int64              `json:"id"`
	ProblemID  int64              `json:"problem_id"`
	Name       string             `json:"name"`
	InputPath  string             `json:"input_path"`
	OutputPath string             `json:"output_path"`
	IsSample   bool               `json:"is_sample"`
	IsHidden   bool               `json:"is_hidden"`
	Score      int32              `json:"score"`
	GroupName  pgtype.Text        `json:"group_name"`
	OrderIndex int32              `json:"order_index"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              int64              `json:"id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Rating          int32              `json:"rating"`
	Bio             string             `json:"bio"`
	IconUrl         pgtype.Text        `json:"icon_url"`
	IsActive        bool               `json:"is_active"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
