// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: problems.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (
  created_by_user_id, title, slug, statement_markdown, time_limit_ms,
  memory_limit_kb, score, difficulty, is_public
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, slug, statement_markdown, time_limit_ms, memory_limit_kb,
          score, difficulty, is_public, created_at, updated_at, created_by_user_id
`

type CreateProblemParams struct {
	CreatedByUserID   pgtype.Int8 `json:"created_by_user_id"`
	Title             string      `json:"title"`
	Slug              string      `json:"slug"`
	StatementMarkdown string      `json:"statement_markdown"`
	TimeLimitMs       int32       `json:"time_limit_ms"`
	MemoryLimitKb     int32       `json:"memory_limit_kb"`
	Score             int32       `json:"score"`
	Difficulty        pgtype.Text `json:"difficulty"`
	IsPublic          bool        `json:"is_public"`
}

type CreateProblemRow struct {
	ID                int64              `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (CreateProblemRow, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.CreatedByUserID,
		arg.Title,
		arg.Slug,
		arg.StatementMarkdown,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.Score,
		arg.Difficulty,
		arg.IsPublic,
	)
	var i CreateProblemRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Score,
		&i.Difficulty,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, slug, statement_markdown, time_limit_ms, memory_limit_kb,
       score, difficulty, is_public, created_at, updated_at, created_by_user_id
FROM problems
WHERE id = $1
`

type GetProblemByIDRow struct {
	ID                int64              `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
}

func (q *Queries) GetProblemByID(ctx context.Context, id int64) (GetProblemByIDRow, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i GetProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Score,
		&i.Difficulty,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, title, slug, statement_markdown, time_limit_ms, memory_limit_kb,
       score, difficulty, is_public, created_at, updated_at, created_by_user_id
FROM problems
WHERE slug = $1
`

type GetProblemBySlugRow struct {
	ID                int64              `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
}

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (GetProblemBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProblemBySlug, slug)
	var i GetProblemBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Score,
		&i.Difficulty,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const listAllProblems = `-- name: ListAllProblems :many
SELECT id, title, slug, statement_markdown, time_limit_ms, memory_limit_kb,
       score, difficulty, is_public, created_at, updated_at, created_by_user_id
FROM problems
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListAllProblemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllProblemsRow struct {
	ID                int64              `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
}

func (q *Queries) ListAllProblems(ctx context.Context, arg ListAllProblemsParams) ([]ListAllProblemsRow, error) {
	rows, err := q.db.Query(ctx, listAllProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProblemsRow
	for rows.Next() {
		var i ListAllProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.StatementMarkdown,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.Score,
			&i.Difficulty,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProblems = `-- name: ListPublicProblems :many
SELECT id, title, slug, statement_markdown, time_limit_ms, memory_limit_kb,
       score, difficulty, is_public, created_at, updated_at, created_by_user_id
FROM problems
WHERE is_public = true
ORDER BY id ASC
`

type ListPublicProblemsRow struct {
	ID                int64              `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
}

func (q *Queries) ListPublicProblems(ctx context.Context) ([]ListPublicProblemsRow, error) {
	rows, err := q.db.Query(ctx, listPublicProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicProblemsRow
	for rows.Next() {
		var i ListPublicProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.StatementMarkdown,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.Score,
			&i.Difficulty,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET title = $2,
    statement_markdown = $3,
    time_limit_ms = $4,
    memory_limit_kb = $5,
    score = $6,
    difficulty = $7,
    is_public = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, title, slug, statement_markdown, time_limit_ms, memory_limit_kb,
          score, difficulty, is_public, created_at, updated_at, created_by_user_id
`

type UpdateProblemParams struct {
	ID                int64       `json:"id"`
	Title             string      `json:"title"`
	StatementMarkdown string      `json:"statement_markdown"`
	TimeLimitMs       int32       `json:"time_limit_ms"`
	MemoryLimitKb     int32       `json:"memory_limit_kb"`
	Score             int32       `json:"score"`
	Difficulty        pgtype.Text `json:"difficulty"`
	IsPublic          bool        `json:"is_public"`
}

type UpdateProblemRow struct {
	ID                int64              `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StatementMarkdown string             `json:"statement_markdown"`
	TimeLimitMs       int32              `json:"time_limit_ms"`
	MemoryLimitKb     int32              `json:"memory_limit_kb"`
	Score             int32              `json:"score"`
	Difficulty        pgtype.Text        `json:"difficulty"`
	IsPublic          bool               `json:"is_public"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (UpdateProblemRow, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.StatementMarkdown,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.Score,
		arg.Difficulty,
		arg.IsPublic,
	)
	var i UpdateProblemRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StatementMarkdown,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.Score,
		&i.Difficulty,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}
