// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ClaimNextJudgeJob(ctx context.Context) (JudgeJob, error)
	CompleteJudgeJob(ctx context.Context, id int64) error
	CreateJudgeJob(ctx context.Context, arg CreateJudgeJobParams) (JudgeJob, error)
	CreateProblem(ctx context.Context, arg CreateProblemParams) (CreateProblemRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateSubmissionResult(ctx context.Context, arg CreateSubmissionResultParams) (SubmissionResult, error)
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSubmissionResults(ctx context.Context, submissionID int64) error
	DeleteTestCase(ctx context.Context, id int64) error
	FailJudgeJob(ctx context.Context, id int64) error
	GetContestBySlug(ctx context.Context, slug string) (Contest, error)
	GetLanguageByID(ctx context.Context, id int64) (Language, error)
	GetProblemByID(ctx context.Context, id int64) (GetProblemByIDRow, error)
	GetProblemBySlug(ctx context.Context, slug string) (GetProblemBySlugRow, error)
	GetSessionByTokenHash(ctx context.Context, sessionTokenHash string) (Session, error)
	GetSubmissionByID(ctx context.Context, id int64) (Submission, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByLogin(ctx context.Context, lower string) (User, error)
	GetUserBySessionTokenHash(ctx context.Context, sessionTokenHash string) (GetUserBySessionTokenHashRow, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	InsertSubmissionResult(ctx context.Context, arg InsertSubmissionResultParams) (SubmissionResult, error)
	ListActiveLanguages(ctx context.Context) ([]Language, error)
	ListAllProblems(ctx context.Context, arg ListAllProblemsParams) ([]ListAllProblemsRow, error)
	ListAllTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error)
	ListContestParticipants(ctx context.Context, contestID int64) ([]ContestParticipant, error)
	ListContestProblems(ctx context.Context, contestID int64) ([]ContestProblem, error)
	ListPublicContests(ctx context.Context) ([]Contest, error)
	ListPublicProblems(ctx context.Context) ([]ListPublicProblemsRow, error)
	ListSampleTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error)
	ListSubmissionResults(ctx context.Context, submissionID int64) ([]SubmissionResult, error)
	ListSubmissionsByProblemID(ctx context.Context, arg ListSubmissionsByProblemIDParams) ([]Submission, error)
	ListSubmissionsByUserID(ctx context.Context, arg ListSubmissionsByUserIDParams) ([]Submission, error)
	ListSubmissionsByUsername(ctx context.Context, arg ListSubmissionsByUsernameParams) ([]Submission, error)
	ListTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVisibleTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error)
	MarkJudgeJobRunning(ctx context.Context, arg MarkJudgeJobRunningParams) (JudgeJob, error)
	RegisterContestParticipant(ctx context.Context, arg RegisterContestParticipantParams) (ContestParticipant, error)
	RequeueStaleJudgeJobs(ctx context.Context, dollar_1 float64) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID int64) error
	RevokeSessionByTokenHash(ctx context.Context, sessionTokenHash string) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error)
	UpdateProblem(ctx context.Context, arg UpdateProblemParams) (UpdateProblemRow, error)
	UpdateSubmissionFinal(ctx context.Context, arg UpdateSubmissionFinalParams) error
	UpdateSubmissionJudged(ctx context.Context, arg UpdateSubmissionJudgedParams) (Submission, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
