// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, session_token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, session_token_hash, user_agent, ip_address,
          expires_at, created_at, revoked_at
`

type CreateSessionParams struct {
	UserID           int64              `json:"user_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	UserAgent        string             `json:"user_agent"`
	IpAddress        string             `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, session_token_hash, user_agent, ip_address,
       expires_at, created_at, revoked_at
FROM sessions
WHERE session_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, sessionTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserBySessionTokenHash = `-- name: GetUserBySessionTokenHash :one
SELECT
  u.id, u.username, u.display_name, u.email, u.password_hash, u.role,
  u.rating, u.bio, u.icon_url, u.is_active, u.email_verified_at,
  u.created_at, u.updated_at,
  s.id, s.user_id, s.session_token_hash, s.user_agent, s.ip_address,
  s.expires_at, s.created_at, s.revoked_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.session_token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.is_active = true
`

type GetUserBySessionTokenHashRow struct {
	ID               int64              `json:"id"`
	Username         string             `json:"username"`
	DisplayName      string             `json:"display_name"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	Role             string             `json:"role"`
	Rating           int32              `json:"rating"`
	Bio              string             `json:"bio"`
	IconUrl          pgtype.Text        `json:"icon_url"`
	IsActive         bool               `json:"is_active"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ID_2             int64              `json:"id_2"`
	UserID           int64              `json:"user_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	UserAgent        string             `json:"user_agent"`
	IpAddress        string             `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt_2      pgtype.Timestamptz `json:"created_at_2"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetUserBySessionTokenHash(ctx context.Context, sessionTokenHash string) (GetUserBySessionTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionTokenHash, sessionTokenHash)
	var i GetUserBySessionTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Rating,
		&i.Bio,
		&i.IconUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID,
		&i.SessionTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt_2,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE session_token_hash = $1
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, sessionTokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, sessionTokenHash)
	return err
}
