// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (user_id, problem_id, language_id, source_code, status)
VALUES ($1, $2, $3, $4, 'WJ')
RETURNING id, user_id, problem_id, language_id, source_code, status, score,
          max_time_ms, max_memory_kb, submitted_at, judged_at
`

type CreateSubmissionParams struct {
	UserID     int64  `json:"user_id"`
	ProblemID  int64  `json:"problem_id"`
	LanguageID int64  `json:"language_id"`
	SourceCode string `json:"source_code"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.LanguageID,
		arg.SourceCode,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.SourceCode,
		&i.Status,
		&i.Score,
		&i.MaxTimeMs,
		&i.MaxMemoryKb,
		&i.SubmittedAt,
		&i.JudgedAt,
	)
	return i, err
}

const createSubmissionResult = `-- name: CreateSubmissionResult :one
INSERT INTO submission_results (
  submission_id, test_case_id, status, execution_time_ms, memory_kb,
  stdout_path, stderr_path, error_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, submission_id, test_case_id, status, execution_time_ms, memory_kb,
          stdout_path, stderr_path, error_message, created_at
`

type CreateSubmissionResultParams struct {
	SubmissionID    int64       `json:"submission_id"`
	TestCaseID      pgtype.Int8 `json:"test_case_id"`
	Status          string      `json:"status"`
	ExecutionTimeMs int32       `json:"execution_time_ms"`
	MemoryKb        int32       `json:"memory_kb"`
	StdoutPath      pgtype.Text `json:"stdout_path"`
	StderrPath      pgtype.Text `json:"stderr_path"`
	ErrorMessage    pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateSubmissionResult(ctx context.Context, arg CreateSubmissionResultParams) (SubmissionResult, error) {
	row := q.db.QueryRow(ctx, createSubmissionResult,
		arg.SubmissionID,
		arg.TestCaseID,
		arg.Status,
		arg.ExecutionTimeMs,
		arg.MemoryKb,
		arg.StdoutPath,
		arg.StderrPath,
		arg.ErrorMessage,
	)
	var i SubmissionResult
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.TestCaseID,
		&i.Status,
		&i.ExecutionTimeMs,
		&i.MemoryKb,
		&i.StdoutPath,
		&i.StderrPath,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubmissionResults = `-- name: DeleteSubmissionResults :exec
DELETE FROM submission_results
WHERE submission_id = $1
`

func (q *Queries) DeleteSubmissionResults(ctx context.Context, submissionID int64) error {
	_, err := q.db.Exec(ctx, deleteSubmissionResults, submissionID)
	return err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, user_id, problem_id, language_id, source_code, status, score,
       max_time_ms, max_memory_kb, submitted_at, judged_at
FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.SourceCode,
		&i.Status,
		&i.Score,
		&i.MaxTimeMs,
		&i.MaxMemoryKb,
		&i.SubmittedAt,
		&i.JudgedAt,
	)
	return i, err
}

const insertSubmissionResult = `-- name: InsertSubmissionResult :one
INSERT INTO submission_results (
  submission_id, test_case_id, status, execution_time_ms, memory_kb,
  stdout_path, stderr_path, error_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, submission_id, test_case_id, status, execution_time_ms, memory_kb,
          stdout_path, stderr_path, error_message, created_at
`

type InsertSubmissionResultParams struct {
	SubmissionID    int64       `json:"submission_id"`
	TestCaseID      pgtype.Int8 `json:"test_case_id"`
	Status          string      `json:"status"`
	ExecutionTimeMs int32       `json:"execution_time_ms"`
	MemoryKb        int32       `json:"memory_kb"`
	StdoutPath      pgtype.Text `json:"stdout_path"`
	StderrPath      pgtype.Text `json:"stderr_path"`
	ErrorMessage    pgtype.Text `json:"error_message"`
}

func (q *Queries) InsertSubmissionResult(ctx context.Context, arg InsertSubmissionResultParams) (SubmissionResult, error) {
	row := q.db.QueryRow(ctx, insertSubmissionResult,
		arg.SubmissionID,
		arg.TestCaseID,
		arg.Status,
		arg.ExecutionTimeMs,
		arg.MemoryKb,
		arg.StdoutPath,
		arg.StderrPath,
		arg.ErrorMessage,
	)
	var i SubmissionResult
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.TestCaseID,
		&i.Status,
		&i.ExecutionTimeMs,
		&i.MemoryKb,
		&i.StdoutPath,
		&i.StderrPath,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listSubmissionResults = `-- name: ListSubmissionResults :many
SELECT id, submission_id, test_case_id, status, execution_time_ms, memory_kb,
       stdout_path, stderr_path, error_message, created_at
FROM submission_results
WHERE submission_id = $1
ORDER BY id ASC
`

func (q *Queries) ListSubmissionResults(ctx context.Context, submissionID int64) ([]SubmissionResult, error) {
	rows, err := q.db.Query(ctx, listSubmissionResults, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubmissionResult
	for rows.Next() {
		var i SubmissionResult
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.TestCaseID,
			&i.Status,
			&i.ExecutionTimeMs,
			&i.MemoryKb,
			&i.StdoutPath,
			&i.StderrPath,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByProblemID = `-- name: ListSubmissionsByProblemID :many
SELECT id, user_id, problem_id, language_id, source_code, status, score,
       max_time_ms, max_memory_kb, submitted_at, judged_at
FROM submissions
WHERE problem_id = $1
ORDER BY submitted_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSubmissionsByProblemIDParams struct {
	ProblemID int64 `json:"problem_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListSubmissionsByProblemID(ctx context.Context, arg ListSubmissionsByProblemIDParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByProblemID, arg.ProblemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.LanguageID,
			&i.SourceCode,
			&i.Status,
			&i.Score,
			&i.MaxTimeMs,
			&i.MaxMemoryKb,
			&i.SubmittedAt,
			&i.JudgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUserID = `-- name: ListSubmissionsByUserID :many
SELECT id, user_id, problem_id, language_id, source_code, status, score,
       max_time_ms, max_memory_kb, submitted_at, judged_at
FROM submissions
WHERE user_id = $1
ORDER BY submitted_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSubmissionsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSubmissionsByUserID(ctx context.Context, arg ListSubmissionsByUserIDParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.LanguageID,
			&i.SourceCode,
			&i.Status,
			&i.Score,
			&i.MaxTimeMs,
			&i.MaxMemoryKb,
			&i.SubmittedAt,
			&i.JudgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUsername = `-- name: ListSubmissionsByUsername :many
SELECT s.id, s.user_id, s.problem_id, s.language_id, s.source_code, s.status,
       s.score, s.max_time_ms, s.max_memory_kb, s.submitted_at, s.judged_at
FROM submissions s
JOIN users u ON u.id = s.user_id
WHERE lower(u.username) = lower($1)
ORDER BY s.submitted_at DESC, s.id DESC
LIMIT $2
`

type ListSubmissionsByUsernameParams struct {
	Lower string `json:"lower"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListSubmissionsByUsername(ctx context.Context, arg ListSubmissionsByUsernameParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUsername, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.LanguageID,
			&i.SourceCode,
			&i.Status,
			&i.Score,
			&i.MaxTimeMs,
			&i.MaxMemoryKb,
			&i.SubmittedAt,
			&i.JudgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionFinal = `-- name: UpdateSubmissionFinal :exec
UPDATE submissions
SET status = $2,
    score = $3,
    max_time_ms = $4,
    max_memory_kb = $5,
    judged_at = now()
WHERE id = $1
`

type UpdateSubmissionFinalParams struct {
	ID          int64  `json:"id"`
	Status      string `json:"status"`
	Score       int32  `json:"score"`
	MaxTimeMs   int32  `json:"max_time_ms"`
	MaxMemoryKb int32  `json:"max_memory_kb"`
}

func (q *Queries) UpdateSubmissionFinal(ctx context.Context, arg UpdateSubmissionFinalParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionFinal,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.MaxTimeMs,
		arg.MaxMemoryKb,
	)
	return err
}

const updateSubmissionJudged = `-- name: UpdateSubmissionJudged :one
UPDATE submissions
SET status = $2,
    score = $3,
    max_time_ms = $4,
    max_memory_kb = $5,
    judged_at = now()
WHERE id = $1
RETURNING id, user_id, problem_id, language_id, source_code, status, score,
          max_time_ms, max_memory_kb, submitted_at, judged_at
`

type UpdateSubmissionJudgedParams struct {
	ID          int64  `json:"id"`
	Status      string `json:"status"`
	Score       int32  `json:"score"`
	MaxTimeMs   int32  `json:"max_time_ms"`
	MaxMemoryKb int32  `json:"max_memory_kb"`
}

func (q *Queries) UpdateSubmissionJudged(ctx context.Context, arg UpdateSubmissionJudgedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionJudged,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.MaxTimeMs,
		arg.MaxMemoryKb,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.SourceCode,
		&i.Status,
		&i.Score,
		&i.MaxTimeMs,
		&i.MaxMemoryKb,
		&i.SubmittedAt,
		&i.JudgedAt,
	)
	return i, err
}
