// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_cases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (
  problem_id, name, input_path, output_path, is_sample, is_hidden,
  score, group_name, order_index
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, problem_id, name, input_path, output_path, is_sample, is_hidden,
          score, group_name, order_index, created_at, updated_at
`

type CreateTestCaseParams struct {
	ProblemID  int64       `json:"problem_id"`
	Name       string      `json:"name"`
	InputPath  string      `json:"input_path"`
	OutputPath string      `json:"output_path"`
	IsSample   bool        `json:"is_sample"`
	IsHidden   bool        `json:"is_hidden"`
	Score      int32       `json:"score"`
	GroupName  pgtype.Text `json:"group_name"`
	OrderIndex int32       `json:"order_index"`
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.ProblemID,
		arg.Name,
		arg.InputPath,
		arg.OutputPath,
		arg.IsSample,
		arg.IsHidden,
		arg.Score,
		arg.GroupName,
		arg.OrderIndex,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Name,
		&i.InputPath,
		&i.OutputPath,
		&i.IsSample,
		&i.IsHidden,
		&i.Score,
		&i.GroupName,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTestCase = `-- name: DeleteTestCase :exec
DELETE FROM test_cases
WHERE id = $1
`

func (q *Queries) DeleteTestCase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTestCase, id)
	return err
}

const listAllTestCasesByProblemID = `-- name: ListAllTestCasesByProblemID :many
SELECT id, problem_id, name, input_path, output_path, is_sample, is_hidden,
       score, group_name, order_index, created_at, updated_at
FROM test_cases
WHERE problem_id = $1
ORDER BY order_index ASC, id ASC
`

func (q *Queries) ListAllTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listAllTestCasesByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Name,
			&i.InputPath,
			&i.OutputPath,
			&i.IsSample,
			&i.IsHidden,
			&i.Score,
			&i.GroupName,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSampleTestCasesByProblemID = `-- name: ListSampleTestCasesByProblemID :many
SELECT id, problem_id, name, input_path, output_path, is_sample, is_hidden,
       score, group_name, order_index, created_at, updated_at
FROM test_cases
WHERE problem_id = $1
  AND is_sample = true
ORDER BY order_index ASC, id ASC
`

func (q *Queries) ListSampleTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listSampleTestCasesByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Name,
			&i.InputPath,
			&i.OutputPath,
			&i.IsSample,
			&i.IsHidden,
			&i.Score,
			&i.GroupName,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesByProblemID = `-- name: ListTestCasesByProblemID :many
SELECT id, problem_id, name, input_path, output_path, is_sample, is_hidden,
       score, group_name, order_index, created_at, updated_at
FROM test_cases
WHERE problem_id = $1
ORDER BY order_index ASC, id ASC
`

func (q *Queries) ListTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Name,
			&i.InputPath,
			&i.OutputPath,
			&i.IsSample,
			&i.IsHidden,
			&i.Score,
			&i.GroupName,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleTestCasesByProblemID = `-- name: ListVisibleTestCasesByProblemID :many
SELECT id, problem_id, name, input_path, output_path, is_sample, is_hidden,
       score, group_name, order_index, created_at, updated_at
FROM test_cases
WHERE problem_id = $1
  AND is_hidden = false
ORDER BY order_index ASC, id ASC
`

func (q *Queries) ListVisibleTestCasesByProblemID(ctx context.Context, problemID int64) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listVisibleTestCasesByProblemID, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCase
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Name,
			&i.InputPath,
			&i.OutputPath,
			&i.IsSample,
			&i.IsHidden,
			&i.Score,
			&i.GroupName,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
